增加Lua函数“Duel.GetRandomNumber()”
purerosefallen/ygopro-core pull request #11
Opened 2022-10-09 10:49 UTC by YSPplayer

●void Duel.GetRandomNumber()
int Duel.GetRandomNumber(int min,int max)
返回min和max之间的1个随机数(包括二者自身)，min最小为0。

2022-10-11 02:58 UTC, purerosefallen commented
LGTM

2022-10-11 02:59 UTC, purerosefallen commented
But please remove all `////zdiy////` blocks.

2022-10-11 03:03 UTC, purerosefallen requested changes

2022-10-11 03:03 UTC, purerosefallen commented on libduel.cpp
> +/////zdiy/////
Remove those blocks.

2022-10-11 03:03 UTC, purerosefallen commented on libduel.cpp
> +	{ "GetRandomNumber", scriptlib::duel_get_random_number },
Put this line at the bottom of extra function block, right below `SetSummonCancelable`

2022-10-11 03:03 UTC, purerosefallen commented on scriptlib.h
> +	static int32 duel_get_random_number(lua_State* L);
Put this line below `static int32 duel_set_summon_cancelable(lua_State *L);`

2022-10-11 06:02 UTC, YSPplayer commented
格式已修改

2023-06-13 00:07 UTC, IMJoyJ commented
Function implemented and this pr should be closed now.

2023-06-13 06:27 UTC, closed without merging